services:
  grafana:
    image: grafana/grafana:latest
    container_name: internet-monitor-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: internet-monitor-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: internet-monitor-blackbox
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml:ro
    restart: unless-stopped
    cap_add:
      - NET_RAW